version: '2'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "13308:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./initdb:/docker-entrypoint-initdb.d:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: youer

