# Generated by Django 2.1.4 on 2019-01-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('type', models.CharField(choices=[('Card', '单词页面')], max_length=100, verbose_name='类型')),
                ('image', models.FileField(upload_to='poster', verbose_name='图片')),
                ('link_url', models.CharField(max_length=100, verbose_name='跳转地址')),
            ],
            options={
                'verbose_name': '海报图',
                'verbose_name_plural': '海报图',
            },
        ),
    ]
