# Generated by Django 2.1.4 on 2019-04-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190312_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='comment',
        ),
    ]
