# Generated by Django 2.1.4 on 2019-01-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardaudio',
            options={'verbose_name': '卡片音频', 'verbose_name_plural': '卡片音频'},
        ),
        migrations.AddField(
            model_name='card',
            name='video',
            field=models.FileField(default=None, max_length=80, upload_to='', verbose_name='卡片视频'),
        ),
    ]
