# Generated by Django 2.1.4 on 2019-01-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20190109_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='voice_num',
            field=models.IntegerField(default=1, verbose_name='发音数量'),
        ),
    ]
