# Generated by Django 2.1.4 on 2019-03-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_cardtype_voice_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardaudio',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='sentence_voice',
            field=models.FileField(blank=True, max_length=80, null=True, upload_to='audio/card', verbose_name='句子发音'),
        ),
        migrations.AddField(
            model_name='card',
            name='word_voice',
            field=models.FileField(blank=True, max_length=80, null=True, upload_to='audio/card', verbose_name='单词发音'),
        ),
        migrations.DeleteModel(
            name='CardAudio',
        ),
    ]
