# Generated by Django 2.1.4 on 2019-03-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20190312_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='word_voice',
        ),
        migrations.AddField(
            model_name='card',
            name='am_word_voice',
            field=models.FileField(blank=True, max_length=80, null=True, upload_to='audio/card', verbose_name='美式发音'),
        ),
        migrations.AddField(
            model_name='card',
            name='en_word_voice',
            field=models.FileField(blank=True, max_length=80, null=True, upload_to='audio/card', verbose_name='英式发音'),
        ),
        migrations.AddField(
            model_name='card',
            name='page_num',
            field=models.IntegerField(default=0, verbose_name='页码'),
        ),
    ]
