# Generated by Django 2.1.4 on 2019-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20190315_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='sentence_voice',
        ),
        migrations.AddField(
            model_name='card',
            name='am_sentence_voice',
            field=models.FileField(blank=True, max_length=80, null=True, upload_to='audio/card', verbose_name='美式句子发音'),
        ),
        migrations.AddField(
            model_name='card',
            name='en_sentence_voice',
            field=models.FileField(blank=True, max_length=80, null=True, upload_to='audio/card', verbose_name='英式句子发音'),
        ),
        migrations.AlterField(
            model_name='card',
            name='am_word_voice',
            field=models.FileField(blank=True, max_length=80, null=True, upload_to='audio/card', verbose_name='美式单词发音'),
        ),
        migrations.AlterField(
            model_name='card',
            name='en_word_voice',
            field=models.FileField(blank=True, max_length=80, null=True, upload_to='audio/card', verbose_name='英式单词发音'),
        ),
    ]
