# Generated by Django 2.1.7 on 2019-04-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20190322_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='voice_num',
            field=models.IntegerField(default=1, verbose_name='发音区域数'),
        ),
    ]
