# Generated by Django 2.1.7 on 2019-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_auto_20190408_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_traget_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cloud图片ID'),
        ),
    ]
