# Generated by Django 2.1.4 on 2019-04-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_card_image_traget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=80, verbose_name='图片名称'),
        ),
    ]
