# Generated by Django 2.1.4 on 2019-04-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_auto_20190430_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='comment',
        ),
    ]
