# Generated by Django 2.2.1 on 2019-06-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_card_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='tag',
        ),
    ]
