# Generated by Django 2.2.1 on 2019-06-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_remove_card_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='标记'),
        ),
    ]
