# Generated by Django 2.2.3 on 2019-07-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_cardtype_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='tag_order',
            field=models.IntegerField(default=1, verbose_name='标记顺序'),
        ),
    ]
