# Generated by Django 2.1.4 on 2019-01-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=80, verbose_name='名称')),
                ('video_url', models.CharField(max_length=80, verbose_name='视频源')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=80, verbose_name='名称')),
                ('image_file', models.FileField(upload_to='', verbose_name='图片')),
            ],
            options={
                'verbose_name': '视频集',
                'verbose_name_plural': '视频集',
            },
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=80, verbose_name='类型名称')),
                ('image_file', models.FileField(upload_to='', verbose_name='图片')),
            ],
            options={
                'verbose_name': '视频类别',
                'verbose_name_plural': '视频类别',
            },
        ),
        migrations.AddField(
            model_name='videolist',
            name='video_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.VideoType'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.VideoList'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.VideoType'),
        ),
    ]
