# Generated by Django 2.1.4 on 2019-01-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=80, verbose_name='名称')),
                ('video_url', models.CharField(max_length=80, verbose_name='视频源')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.RemoveField(
            model_name='videolist',
            name='video_type',
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频集', 'verbose_name_plural': '视频集'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_list',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='has_subvideo',
            field=models.BooleanField(default=False, verbose_name='是否有子视频'),
        ),
        migrations.AddField(
            model_name='video',
            name='image_file',
            field=models.FileField(default='', upload_to='', verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.VideoType'),
        ),
        migrations.DeleteModel(
            name='VideoList',
        ),
        migrations.AddField(
            model_name='subvideo',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
