# Generated by Django 2.1.4 on 2019-01-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190123_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subvideo',
            options={'verbose_name': '子视频', 'verbose_name_plural': '子视频'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
    ]
