# Generated by Django 2.1.4 on 2019-01-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190123_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.FileField(default='', max_length=80, upload_to='', verbose_name='视频源'),
            preserve_default=False,
        ),
    ]
