# Generated by Django 2.1.4 on 2019-01-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20190123_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvideo',
            name='video_url',
            field=models.FileField(max_length=80, upload_to='', verbose_name='视频源'),
        ),
    ]
