# Generated by Django 2.1.4 on 2019-01-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20190123_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvideo',
            name='image_url',
            field=models.FileField(default='', max_length=80, upload_to='', verbose_name='展示图片'),
            preserve_default=False,
        ),
    ]
