# Generated by Django 2.1.4 on 2019-01-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_subvideo_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvideo',
            name='description',
            field=models.TextField(default='', verbose_name='描述'),
            preserve_default=False,
        ),
    ]
