# Generated by Django 2.1.4 on 2019-04-30 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_subvideo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvideo',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Video', verbose_name='所属视频'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.VideoType', verbose_name='视频类型'),
        ),
    ]
