# Generated by Django 2.1.4 on 2019-04-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20190430_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subvideo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='video',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='videotype',
            name='comment',
        ),
    ]
